In [2]:
import pandas as pd
import numpy as np

In [70]:
def extract_pos_coordinates(filepath, columns_to_extract=None, output_csv=None):
    """
    Extract specified columns from a position file.
    
    Parameters:
    - filepath: Path to the input file
    - columns_to_extract: List of column indices to extract (0-based). 
                         If None, extracts first 4 columns by default.
    - output_csv: Optional path to save results as CSV
    """
    if columns_to_extract is None:
        columns_to_extract = [0, 1, 2, 3]  # Default: first 4 columns
    
    extracted_rows = []
    column_names = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip metadata and comments
            if not line or line.startswith('%'):
                continue
            
            # Extract and clean the comma-separated values
            parts = [p.strip() for p in line.split(',')]
            
            # Extract only the specified columns
            try:
                extracted_values = []
                for col_idx in columns_to_extract:
                    if col_idx < len(parts):
                        # Try to convert to float, otherwise keep as string
                        try:
                            extracted_values.append(float(parts[col_idx]))
                        except ValueError:
                            extracted_values.append(parts[col_idx])
                    else:
                        extracted_values.append(None)  # or '' for empty string
                
                extracted_rows.append(extracted_values)
            except (IndexError, ValueError) as e:
                print(f"Warning: Skipping line due to error: {e}")
                print(f"Line content: {line}")
                continue

    # Optional: write to CSV
    if output_csv:
        import csv
        # Generate column headers based on indices
        column_names = [f'Column_{idx}' for idx in columns_to_extract]
        
        with open(output_csv, 'w', newline='') as f_out:
            writer = csv.writer(f_out)
            writer.writerow(column_names)
            writer.writerows(extracted_rows)

    return extracted_rows

# Example usage
pos_file_path = r'F:\zizo\RTKCorrection\src\research\research_data\testKinematic.pos'



# Example 3: Extract with CSV output
output3 = extract_pos_coordinates(
    pos_file_path, 
    columns_to_extract=[0, 1, 2, 3],  # GPST, Latitude, Longitude
    output_csv='extracted_coordinates.csv'
)

pd.set_option('display.precision', 10)
df_y = pd.DataFrame(output3, columns=['GPST', 'x_y', 'y_y', 'z_y'])

In [4]:
df_y = pd.read_csv(r'F:\zizo\RTKCorrection\src\research\extracted_coordinates_yGPS.csv')
df_y.head()
#df_y.to_csv('extracted_coordinates_y.csv', index=False)

                     GPST          x_y           y_y           z_y
0  2024/02/14 04:19:28.00  461329.7966  5.634437e+06  2.945930e+06
1  2024/02/14 04:19:29.00  461329.7978  5.634437e+06  2.945930e+06
2  2024/02/14 04:19:30.00  461329.7970  5.634437e+06  2.945930e+06
3  2024/02/14 04:19:31.00  461329.7973  5.634437e+06  2.945930e+06
4  2024/02/14 04:19:32.00  461329.7976  5.634437e+06  2.945930e+06

In [5]:
df_x = pd.read_csv(r'F:\zizo\RTKCorrection\src\research\extracted_coordinates_xGPS.csv')
df_x.head()

,GPST,x_x,y_x,z_x,ns,sdx(m),sdy(m),sdz(m),sdxy(m),sdyz(m),sdzx(m)
0,2024/02/14 04:19:28.00,461331.6142,5.634448e+06,2.945937e+06,5.0,7.3944,26.3075,26.4926,3.3154,25.2288,-5.0914
1,2024/02/14 04:19:29.00,461331.5748,5.634447e+06,2.945937e+06,5.0,7.3939,26.3098,26.4915,3.3125,25.2298,-5.0906
2,2024/02/14 04:19:30.00,461331.5861,5.634447e+06,2.945937e+06,5.0,7.3934,26.3120,26.4904,3.3095,25.2308,-5.0898
3,2024/02/14 04:19:31.00,461331.6168,5.634447e+06,2.945936e+06,5.0,7.3929,26.3143,26.4892,3.3066,25.2318,-5.0890
4,2024/02/14 04:19:32.00,461331.6133,5.634447e+06,2.945936e+06,5.0,7.3924,26.3165,26.4881,3.3037,25.2328,-5.0882

In [72]:
pos_file_path2 = r'F:\zizo\RTKCorrection\src\research\research_data\testsSPP.pos'
output3 = extract_pos_coordinates(
    pos_file_path2, 
    columns_to_extract=[0, 1, 2, 3, 5, 6, 7, 8],  # GPST, Latitude, Longitude
    output_csv='extracted_coordinates.csv'
)
df_x = pd.DataFrame(output3, columns=['GPST', 'x_x', 'y_x', 'z_x', 'ns','sdx(m)','sdy(m)','sdz(m)'])
#df_x.to_csv('extracted_coordinates_x.csv', index=False)

In [73]:
df_x.tail()

,GPST,x_x,y_x,z_x,ns,sdx(m),sdy(m),sdz(m)
7968,2024/02/14 06:32:20.01,464124.0612,5.6326319059e+06,2.9490136174e+06,12.0,6.0030,21.8619,8.2872
7969,2024/02/14 06:32:21.01,464124.1856,5.6326333853e+06,2.9490157864e+06,12.0,6.0032,21.8594,8.2869
7970,2024/02/14 06:32:22.01,464124.7210,5.6326347517e+06,2.9490175730e+06,11.0,10.7966,30.3993,11.5897
7971,2024/02/14 06:32:23.01,464132.2236,5.6326295838e+06,2.9490205933e+06,11.0,10.7976,30.3961,11.5892
7972,2024/02/14 06:32:24.01,464116.7796,5.6326436905e+06,2.9490250465e+06,7.0,19.6735,34.7704,15.2285

# EDA

In [6]:
df = pd.merge(df_x, df_y, on='GPST', how='inner', suffixes=('_x', '_y'))

In [7]:
df.head()

,GPST,x_x,y_x,z_x,ns,sdx(m),sdy(m),sdz(m),sdxy(m),sdyz(m),sdzx(m),x_y,y_y,z_y
0,2024/02/14 04:19:28.00,461331.6142,5.634448e+06,2.945937e+06,5.0,7.3944,26.3075,26.4926,3.3154,25.2288,-5.0914,461329.7966,5.634437e+06,2.945930e+06
1,2024/02/14 04:19:29.00,461331.5748,5.634447e+06,2.945937e+06,5.0,7.3939,26.3098,26.4915,3.3125,25.2298,-5.0906,461329.7978,5.634437e+06,2.945930e+06
2,2024/02/14 04:19:30.00,461331.5861,5.634447e+06,2.945937e+06,5.0,7.3934,26.3120,26.4904,3.3095,25.2308,-5.0898,461329.7970,5.634437e+06,2.945930e+06
3,2024/02/14 04:19:31.00,461331.6168,5.634447e+06,2.945936e+06,5.0,7.3929,26.3143,26.4892,3.3066,25.2318,-5.0890,461329.7973,5.634437e+06,2.945930e+06
4,2024/02/14 04:19:32.00,461331.6133,5.634447e+06,2.945936e+06,5.0,7.3924,26.3165,26.4881,3.3037,25.2328,-5.0882,461329.7976,5.634437e+06,2.945930e+06

In [8]:
df.isna().sum()

GPST       0
x_x        0
y_x        0
z_x        0
ns         0
sdx(m)     0
sdy(m)     0
sdz(m)     0
sdxy(m)    0
sdyz(m)    0
sdzx(m)    0
x_y        0
y_y        0
z_y        0
dtype: int64

In [9]:
print(df['x_x'].max() - df['x_x'].min())
print(df['y_x'].max() - df['y_x'].min())
print(df['z_x'].max() - df['z_x'].min())

6509.645799999998
4051.8719999995083
7957.535500000231

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7525 entries, 0 to 7524
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GPST     7525 non-null   object
 1   x_x      7525 non-null   float64
 2   y_x      7525 non-null   float64
 3   z_x      7525 non-null   float64
 4   ns       7525 non-null   float64
 5   sdx(m)   7525 non-null   float64
 6   sdy(m)   7525 non-null   float64
 7   sdz(m)   7525 non-null   float64
 8   sdxy(m)  7525 non-null   float64
 9   sdyz(m)  7525 non-null   float64
 10  sdzx(m)  7525 non-null   float64
 11  x_y      7525 non-null   float64
 12  y_y      7525 non-null   float64
 13  z_y      7525 non-null   float64
dtypes: float64(13), object(1)
memory usage: 823.2+ KB

# Feature Engineering

In [11]:

def feature_engineers(df):
    # calculate correction position
    df['diff_x_y'] = (df['x_y'] - df['x_x']) 
    df['diff_y_y']  = (df['y_y'] - df['y_x']) 
    df['diff_z_y']    = df['z_y'] - df['z_x']

    # Convert GPST to datetime and calculate elapsed time in seconds
    df['GPST'] = pd.to_datetime(df['GPST'], format='%Y/%m/%d %H:%M:%S.%f')
    df['time_elapsed'] = (df['GPST'] - df['GPST'].iloc[0]).dt.total_seconds()

    # Compute speed = distance / time
    df['dx'] = df['x_x'].diff()
    df['dy'] = df['y_y'].diff()
    df['dz'] = df['z_y'].diff()
    df['dt'] = df['time_elapsed'].diff()
    df['v_x'] = df['dx'] / df['dt']
    df['v_y'] = df['dy'] / df['dt']
    df['v_z'] = df['dz'] / df['dt']
    df['distance'] = np.sqrt(df['dx']**2 + df['dy']**2 + df['dz']**2)
    df['speed'] = df['distance'] / df['dt']
    df=df.drop(columns=['dx','dy','dz','distance','dt'],axis = 1)

    df['x_lag1'] = df['x_x'].shift(1)
    df['y_lag1'] = df['y_x'].shift(1)
    df['z_lag1'] = df['z_x'].shift(1)
    
    return df
df = feature_engineers(df)
df.head()

,GPST,x_x,y_x,z_x,ns,sdx(m),sdy(m),sdz(m),sdxy(m),sdyz(m),...,diff_y_y,diff_z_y,time_elapsed,v_x,v_y,v_z,speed,x_lag1,y_lag1,z_lag1
0,2024-02-14 04:19:28,461331.6142,5.634448e+06,2.945937e+06,5.0,7.3944,26.3075,26.4926,3.3154,25.2288,...,-10.6526,-6.9683,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-02-14 04:19:29,461331.5748,5.634447e+06,2.945937e+06,5.0,7.3939,26.3098,26.4915,3.3125,25.2298,...,-10.2118,-6.5668,1.0,-0.0394,0.0051,0.0035,0.039883,461331.6142,5.634448e+06,2.945937e+06
2,2024-02-14 04:19:30,461331.5861,5.634447e+06,2.945937e+06,5.0,7.3934,26.3120,26.4904,3.3095,25.2308,...,-9.9628,-6.2142,2.0,0.0113,-0.0013,0.0020,0.011549,461331.5748,5.634447e+06,2.945937e+06
3,2024-02-14 04:19:31,461331.6168,5.634447e+06,2.945936e+06,5.0,7.3929,26.3143,26.4892,3.3066,25.2318,...,-9.9122,-6.1068,3.0,0.0307,0.0011,-0.0009,0.030733,461331.5861,5.634447e+06,2.945937e+06
4,2024-02-14 04:19:32,461331.6133,5.634447e+06,2.945936e+06,5.0,7.3924,26.3165,26.4881,3.3037,25.2328,...,-9.7324,-5.9221,4.0,-0.0035,-0.0091,-0.0085,0.012935,461331.6168,5.634447e+06,2.945936e+06

In [14]:
df['diff_z_y'].describe()

count    7525.000000
mean      -17.868701
std         5.165438
min       -40.779700
25%       -21.101100
50%       -18.040300
75%       -14.306500
max        14.263600
Name: diff_z_y, dtype: float64

## Removing first row to avoid NaN values in diff columns

In [15]:
df = df.drop(index=0)
df.head()

,GPST,x_x,y_x,z_x,ns,sdx(m),sdy(m),sdz(m),sdxy(m),sdyz(m),...,diff_y_y,diff_z_y,time_elapsed,v_x,v_y,v_z,speed,x_lag1,y_lag1,z_lag1
1,2024-02-14 04:19:29,461331.5748,5.634447e+06,2.945937e+06,5.0,7.3939,26.3098,26.4915,3.3125,25.2298,...,-10.2118,-6.5668,1.0,-0.0394,0.0051,0.0035,0.039883,461331.6142,5.634448e+06,2.945937e+06
2,2024-02-14 04:19:30,461331.5861,5.634447e+06,2.945937e+06,5.0,7.3934,26.3120,26.4904,3.3095,25.2308,...,-9.9628,-6.2142,2.0,0.0113,-0.0013,0.0020,0.011549,461331.5748,5.634447e+06,2.945937e+06
3,2024-02-14 04:19:31,461331.6168,5.634447e+06,2.945936e+06,5.0,7.3929,26.3143,26.4892,3.3066,25.2318,...,-9.9122,-6.1068,3.0,0.0307,0.0011,-0.0009,0.030733,461331.5861,5.634447e+06,2.945937e+06
4,2024-02-14 04:19:32,461331.6133,5.634447e+06,2.945936e+06,5.0,7.3924,26.3165,26.4881,3.3037,25.2328,...,-9.7324,-5.9221,4.0,-0.0035,-0.0091,-0.0085,0.012935,461331.6168,5.634447e+06,2.945936e+06
5,2024-02-14 04:19:33,461331.7199,5.634447e+06,2.945936e+06,5.0,7.3919,26.3187,26.4869,3.3008,25.2337,...,-9.7639,-5.8084,5.0,0.1066,0.0027,0.0025,0.106663,461331.6133,5.634447e+06,2.945936e+06

In [16]:
"""x1 = df[['x_x','ns','sdx(m)','x_lag1']]
x2 = df[['y_x','ns','sdy(m)','y_lag1']]
x3 = df[['z_x','ns','sdz(m)','z_lag1']]

y1 = df['x_y']
y2 = df['y_y']
y3 = df['z_y']"""

x = df[['x_x', 'y_x', 'z_x', 'ns', 'sdx(m)', 'sdy(m)', 'sdz(m)']]
y = df[['x_y','y_y','z_y']]

In [17]:
feature_cols = [col for col in df.columns if col.lower() in ['x_x', 'y_x', 'z_x', 'ns', 'sdx(m)', 'sdy(m)', 'sdz(m)']]

# Model Training

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
import numpy as np



def model_trainer(X, y, test_size=0.2, random_state=42):
    """
    Train a Random Forest model with feature standardization
    """
    indices = np.arange(X.shape[0])

    X_train, X_test, y_train, y_test, indices_train, indices_test = train_test_split(
        X, y, indices, test_size=test_size, random_state=random_state
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    print(f"\nTraining Random Forest model for multi-output regression...")
    rf_model = RandomForestRegressor(n_estimators=100, random_state=random_state, max_depth=10, oob_score=True)
    rf_model.fit(X_train_scaled, y_train)

    print("Model training complete.")
    
    # Predict
    y_pred = rf_model.predict(X_test_scaled)

    print("\n" + "="*80)
    print("RANDOM FOREST MULTI-OUTPUT MODEL EVALUATION")
    print("="*80)

    # Handle single output vs multi-output
    if y_pred.ndim == 1:
        # Single output
        r2 = r2_score(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        mae = mean_absolute_error(y_test, y_pred)
        print(f"Test R² Score: {r2:.4f}")
        print(f"RMSE (meters): {rmse:.4f}")
        print(f"MAE (meters):  {mae:.4f}")
    else:
        # Multi-output
        axes = ['X', 'Y', 'Z'][:y_pred.shape[1]]  # Adjust based on actual number of outputs
        for i, axis in enumerate(axes):
            r2 = r2_score(y_test.iloc[:, i] if hasattr(y_test, 'iloc') else y_test[:, i], 
                         y_pred[:, i])
            rmse = np.sqrt(mean_squared_error(y_test.iloc[:, i] if hasattr(y_test, 'iloc') else y_test[:, i], 
                                            y_pred[:, i]))
            mae = mean_absolute_error(y_test.iloc[:, i] if hasattr(y_test, 'iloc') else y_test[:, i], 
                                    y_pred[:, i])
            print(f"--- Axis {axis} ---")
            print(f"  Test R² Score: {r2:.4f}")
            print(f"  RMSE (meters): {rmse:.4f}")
            print(f"  MAE (meters):  {mae:.4f}\n")

    if hasattr(rf_model, 'oob_score_'):
        print(f"Overall Out-of-Bag (OOB) Score: {rf_model.oob_score_:.4f}")
    
    return rf_model, scaler, y_pred, X_test_scaled, y_test

# Usage example:
model, scaler, y_pred1, X_test_scaled1, y_test1 = model_trainer(x, y)

# Usage example:
#model, y_pred1, X_test1, y_test1 = model_trainer(x1, y1)

#y_pred1 = model_traner(X_train1, y_train1, X_test1, y_test1)

Training Random Forest model for multi-output regression...
Model training complete.

================================================================================
RANDOM FOREST MULTI-OUTPUT MODEL EVALUATION
================================================================================
--- Axis X ---
  Test R² Score: 1.0000
  RMSE (meters): 4.4024
  MAE (meters):  2.1141

--- Axis Y ---
  Test R² Score: 1.0000
  RMSE (meters): 2.7724
  MAE (meters):  1.6266

--- Axis Z ---
  Test R² Score: 1.0000
  RMSE (meters): 4.0372
  MAE (meters):  2.3342

Overall Out-of-Bag (OOB) Score: 1.0000

In [19]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Suppose you have true and predicted arrays for x, y, z
true_coords = np.column_stack([y_test1, y_test2, y_test3])
pred_coords = np.column_stack([y_pred1, y_pred2, y_pred3])

# Compute Euclidean errors per sample
errors_3d = np.linalg.norm(pred_coords - true_coords, axis=1)

# Overall metrics
rmse_3d = np.sqrt(np.mean(errors_3d**2))
mae_3d = np.mean(errors_3d)
bias_3d = np.mean(errors_3d - np.mean(errors_3d))  # optional, often bias = 0

print(f"RMSE₃D: {rmse_3d:.4f} m")
print(f"MAE₃D : {mae_3d:.4f} m")

NameError: name 'y_test2' is not defined